.TH TWIN 3
.SH NAME
.PP
TWIN - Terminal Windows Library
.SH SYNOPSIS
.PP
.nf
#include <windows.h>

void    del_win(win)
win_t   **win;

.fi
.SH DESCRIPTION

.B del_win
frees all memory used by the window pointed to by
.B *win,
and sets *win to NULL.

Note that del_win() takes the
.B address
of a window pointer, as shown in the example below.  This allows the
pointer to be set to NULL by del_win().

.SH EXAMPLE

    #include <windows.h>

    int     main()

    {
        term_t  *term;
        win_t   *win;
    
        /* Initialize terminal */
        term = init_term(stdin,stdout,stderr,NULL);
    
        /* Create a new window */
        win = new_win(term,10,60,2,2);
    
        /* Print a message in the window */
        wprintf(win,"Hello, world!\\n");
    
        /* Delete the window */
        del_win(&win);
    
        return 0;
    }

.SH PITFALLS

.B del_win()
takes the
.B address
of a
.B win_t
pointer, not just a win_t pointer.  Misuse will generate a warning
from most compilers.  The
.B -Wall
option is recommended with
.B gcc.

.SH FILES

libtwin.a, windows.h, terminal.h, image.h
.SH SEE\ ALSO

twin, termcap, terminfo, cc, ld, curses, ioctl, sgtty, termio, termios
.SH AUTHOR

Jason W. Bacon
