.TH TWIN 3
.SH NAME
.PP
TWIN - Terminal Windows Library
.SH SYNOPSIS
.PP
.nf
#include <windows.h>

win_t   *wmessage_win(term,message,fg,bg,attr)
term_t  *term;
char    *message[];
unsigned    fg,bg,attr;

.fi
.SH WHAT\ IT\ IS
.SH DESCRIPTION
.cu
PARAMETERS:

.SH RETURN\ VALUE
.SH PITFALLS
.SH EXAMPLE
.SH FILES

libtwin.a, windows.h, terminal.h, image.h
.SH SEE\ ALSO

twin, termcap, terminfo, cc, ld, curses, ioctl, sgtty, termio, termios
.SH AUTHOR

Jason W. Bacon
