.TH TWIN 3
.SH NAME
.PP
TWIN - Terminal Windows Library
.SH SYNOPSIS
.PP
.nf
#include <windows.h>

void        shadow(win,use_color)
win_t       *win;
unsigned    use_color;

.fi
.SH WHAT\ IT\ IS
.SH DESCRIPTION
.cu
PARAMETERS:

.SH RETURN\ VALUE
.SH PITFALLS
.SH EXAMPLE
.SH FILES

libtwin.a, windows.h, terminal.h, image.h
.SH SEE\ ALSO

twin, termcap, terminfo, cc, ld, curses, ioctl, sgtty, termio, termios
.SH AUTHOR

Jason W. Bacon
