.TH TWIN 3
.SH NAME
.PP
TWIN - Terminal Windows Library
.SH SYNOPSIS
.PP
.nf
#include <windows.h>

int     tset_modes(terminal,mode)
term_t  *terminal;
int     mode;

.fi
.SH DESCRIPTION
.SH EXAMPLE
.SH FILES

libtwin.a, windows.h, terminal.h, image.h
.SH SEE ALSO

twin, termcap, terminfo, cc, ld, curses, ioctl, sgtty, termio, termios
.SH AUTHOR

Jason W. Bacon
